# This is a basic workflow to help you get started with Actions

name: Reviewdog

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the trunk branch
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  languagetool:
    name: runner / languagetool
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: reviewdog/action-languagetool@v1
          with:
            github_token: ${{ secrets.github_token }}
            reporter: github-check
            level: info
            patterns: |
              **/*.md
              **/*.c
              **/*.rst
              !**/testdata/**

  formater:
    name: runner / code style
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup Requirements
          run: apt update && apt install astyle
        - name: Run Formating
          run: |
            find -iname "*.c" -exec astyle --indent=spaces=4 --style=attach -n --max-code-length=120 -xf -xh {} \;
            find -iname "*.cpp" -exec astyle --indent=spaces=4 --style=attach -n --max-code-length=120 -xf -xh {} \;
        - uses: reviewdog/action-suggester@v1
          with:
            tool_name: astyle
